### PR TITLE
✨ v3 press-kit

### PR DESCRIPTION
**Pull request by roiLeo**
- missing K. Logo export
- missing svg export

#### Related
- #16 
- #17 
- https://github.com/kodadot/nft-gallery/issues/1449

### CODE REVIEW

**Comment by XyloDrone** [comment]
Everything exported in #16

**Comment by jkdizajn** [comment]
> Everything exported in #16
@XyloDone
Please if possible upload in curves, real SVG, these are all PNG bitmap images in SVG file :( 
https://github.com/kodadot/kodadot-presskit/tree/main/v3

obrázok

**Comment by XyloDrone** [comment]
Not sure why this keeps happening. Hope these work:
[Koda_SVG_Logo_Export.zip](https://github.com/kodadot/kodadot-presskit/files/7837638/Koda_SVG_Logo_Export.zip)

**Comment by roiLeo** [comment]
> Not sure why this keeps happening. Hope these work: [Koda_SVG_Logo_Export.zip](https://github.com/kodadot/kodadot-presskit/files/7837638/Koda_SVG_Logo_Export.zip)

I think your export went wrong:
Capture d’écran 2022-01-10 à 9 56 59 AM

**Comment by XyloDrone** [comment]
This is very odd as neither of the logos look like that when I open them. I redownloaded my own file and it looks fine.

**Comment by XyloDrone** [comment]
Is anyone else gettting this? 

>

**Comment by roiLeo** [comment]
> This is very odd as neither of the logos look like that when I open them. I redownloaded my own file and it looks fine.

Your files contain the definition of the font-style, if I don't have the font installed on my computer it won't show as excepted.

**Comment by XyloDrone** [comment]
I see. I hope this is finally it: 
[KodaDot_SVG Export_v2.zip](https://github.com/kodadot/kodadot-presskit/files/7837778/KodaDot_SVG.Export_v2.zip)

**Comment by roiLeo** [comment]
> I see. I hope this is finally it: [KodaDot_SVG Export_v2.zip](https://github.com/kodadot/kodadot-presskit/files/7837778/KodaDot_SVG.Export_v2.zip)

Perfect!

**Comment by jkdizajn** [comment]
> I see. I hope this is finally it: [KodaDot_SVG Export_v2.zip](https://github.com/kodadot/kodadot-presskit/files/7837778/KodaDot_SVG.Export_v2.zip)

Nice, this is vector <3

**Pull request merged**
