### PR TITLE
Create V1_Kodadot Logo and Guides

### PR DESCRIPTION
**Pull request by XyloDrone**
kodadot logo
kodadot logo2
kodadot logo3
kodadot logo4
kodadot logo5
kodadot logo6
kodadot logo7
kodadot logo8

### CODE REVIEW

**Comment by XyloDrone** [comment]
kodadot logo bw
kodadot logo WB
)
kodadot logo full name
kodadot logo full name on white
kodadot logo full name bw

kodadot logo full name wb

**Comment by XyloDrone** [comment]
[Kodadot Brand guidelines.pdf](https://github.com/kodadot/presskit/files/7198460/Kodadot.Brand.guidelines.pdf)

**Comment by yangwao** [comment]
LGTM 👀

køda ł

**Comment by roiLeo** [comment]
Hey! could we have svg version?

**Comment by yangwao** [comment]
Added all logos to v2 folder -- https://github.com/kodadot/kodadot-presskit/tree/main/v2


> Hey! could we have svg version?

Continue here @roiLeo  hope someone (@XyloDrone) will deliver! https://github.com/kodadot/kodadot-presskit/issues/15

**Pull request merged**
